#!/bin/sh

if [ "$2" != "POST-DEINSTALL" ]; then
    exit 0
fi

USER={{package_install_user}}

if pw usershow "${USER}" 2>/dev/null 1>&2; then
        echo "To delete {{package_name}} user permanently, use 'pw userdel ${USER}'"
fi

exit 0
