
##
## Export all variables to sub-invocation
##
export

bootstrap:
	ln -sf $(PKG_ID).tar.gz $(PKG_NAME)_$(PKG_VERSION).orig.tar.gz
	mkdir -p $(PKG_ID)/solaris
	cd $(PKG_ID)/solaris && $(REBAR) -v create \
                              package_name=$(PKG_NAME) \
                              template_dir=../deps/node_package/priv/templates \
                              template_vars=../pkg.vars.config template=solaris
	$(MAKE) -C $(PKG_ID) -f solaris/Makefile
