
##
## Export all variables to sub-invocation
##
export

default:
	ln -sf $(TAG).tar.gz $(REVISION).orig.tar.gz
	mkdir -p $(TAG)/debian
	cd $(TAG)/debian && $(REBAR) -v create \
                              template_dir=../deps/node_package/priv/templates \
                              template_vars=../pkg.vars.config template=deb
	make -C $(TAG) -f debian/Makefile
